# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubesealplus < Formula
  desc "A kubeseal wrapper which makes working with Sealed Secrets and Helm a breeze."
  homepage "https://github.com/ryan0x44/kubesealplus"
  version "0.2.0"
  license "MIT"

  depends_on "kubeseal"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ryan0x44/kubesealplus/releases/download/v0.2.0/kubesealplus_Darwin_arm64.tar.gz"
      sha256 "e4ce348e6ad8af6a362241b80f559f1a38452be0ae4bcfdea02d4fb70401ff06"

      def install
        bin.install "kubesealplus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryan0x44/kubesealplus/releases/download/v0.2.0/kubesealplus_Darwin_x86_64.tar.gz"
      sha256 "0eaf196cbee9deb8f7c4e404b2269b563bd17a7c7e09f01630827b102736478d"

      def install
        bin.install "kubesealplus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryan0x44/kubesealplus/releases/download/v0.2.0/kubesealplus_Linux_arm64.tar.gz"
      sha256 "cc3192d6bdcb900467232c268992a1a324011c3723fcc9a260d8996d01b39889"

      def install
        bin.install "kubesealplus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryan0x44/kubesealplus/releases/download/v0.2.0/kubesealplus_Linux_x86_64.tar.gz"
      sha256 "5c036bb701f754831fc2626ec206db7fa19f273fedd4bf36922cd56fa9498209"

      def install
        bin.install "kubesealplus"
      end
    end
  end
end
