# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubesealplus < Formula
  desc "A kubeseal wrapper which makes working with Sealed Secrets and Helm a breeze."
  homepage "https://github.com/ryan0x44/kubesealplus"
  version "0.2.1"
  license "MIT"

  depends_on "kubeseal"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ryan0x44/kubesealplus/releases/download/v0.2.1/kubesealplus_Darwin_arm64.tar.gz"
      sha256 "6374a6636dc9204d11cc50591b8c1410220f522f9b72e6f8cea4a32d87d25065"

      def install
        bin.install "kubesealplus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryan0x44/kubesealplus/releases/download/v0.2.1/kubesealplus_Darwin_x86_64.tar.gz"
      sha256 "ef2b19d3d64c83b4d3e0bfc4532b5fdc4bb28558dad33e9344d7338e438186c0"

      def install
        bin.install "kubesealplus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryan0x44/kubesealplus/releases/download/v0.2.1/kubesealplus_Linux_arm64.tar.gz"
      sha256 "61b48419fab49f35809810a7eefc7bb868b9d217ca6f5b75306e8760861910ab"

      def install
        bin.install "kubesealplus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryan0x44/kubesealplus/releases/download/v0.2.1/kubesealplus_Linux_x86_64.tar.gz"
      sha256 "cc8c16f95f02ea88125acb785bb27095da9c0d28fd34952f1d93eb8863ba065b"

      def install
        bin.install "kubesealplus"
      end
    end
  end
end
